### ISSUE TITLE
CSS media queries

### ISSUE THREAD

**Issue by tacotoemeck** [fac19/week8-DEKN#48]
There's an issue ( I think :thinking:  ) with this media query, it repeats on multiple lines whenever media query is used. Is there a reason for it?

```css
@media screen and (max-width: 767px) {
    .navbar {
        width: 80vw;
    }

    box-sizing: border-box; /*<=== is that meant to be here?*/
}
```
